# Header
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  Repo: /repo

# favicon
favicon: /images/logo.svg

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/dethMastery
  # ZhiHu:
  Twitter: https://twitter.com/JojiDetzz
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# disqusjs
disqusjs:
  enable: false
  api:
  apikey:
  shortname:
